spring:
  profiles:
    active: local
#for run on local/development
#      active: prod #for prod using environmrnt
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    active:
        on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dashboard
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    database: default
    #     show-sql: true
    #      properties:
    #         hibernate:
    #            format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 60m


